FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["SalesApp.Api.csproj", "."]
RUN dotnet restore "./SalesApp.Api.csproj"
COPY . .
RUN dotnet build "SalesApp.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SalesApp.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SalesApp.Api.dll"]
