user nginx;
worker_processes auto;

events { worker_connections 1024; }

http {
  client_max_body_size 50M;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    server_name localhost;

    # Backend Proxy (E2E)
    location /api {
      set $backend http://salesapp-api-e2e:5000;
      proxy_pass $backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend Proxy (E2E)
    location / {
      set $frontend http://salesapp-client-e2e:80;
      proxy_pass $frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
