using SalesApp.Services;
using Xunit;
using FluentAssertions;

namespace SalesApp.Tests.Services
{
    public class CsvDelimiterDetectorTests
    {
        // ---------------------------------------------------------------
        // Method 1 — Frequency analysis
        // ---------------------------------------------------------------

        [Fact]
        public void Method1_CommaFile_ReturnsComma()
        {
            var result = CsvDelimiterDetector.Method1_FrequencyAnalysis("Name,Email,Matricula");
            result.Should().Be(',');
        }

        [Fact]
        public void Method1_SemicolonFile_ReturnsSemicolon()
        {
            var result = CsvDelimiterDetector.Method1_FrequencyAnalysis("Name;Email;Matricula");
            result.Should().Be(';');
        }

        [Fact]
        public void Method1_EqualCounts_ReturnsNull()
        {
            // one comma, one semicolon → tie
            var result = CsvDelimiterDetector.Method1_FrequencyAnalysis("Name,Email;Matricula");
            result.Should().BeNull();
        }

        [Fact]
        public void Method1_QuotedFieldsIgnored()
        {
            // comma inside quotes should not be counted
            var result = CsvDelimiterDetector.Method1_FrequencyAnalysis("\"Last,First\";Email;Matricula");
            result.Should().Be(';');
        }

        // ---------------------------------------------------------------
        // Method 2 — Field-count consistency
        // ---------------------------------------------------------------

        [Fact]
        public void Method2_CommaSplitConsistent_ReturnsComma()
        {
            var header = "Name,Email,Matricula";
            var row = "Arthur,,6111";
            var result = CsvDelimiterDetector.Method2_FieldCountConsistency(header, row);
            result.Should().Be(',');
        }

        [Fact]
        public void Method2_SemicolonSplitConsistent_ReturnsSemicolon()
        {
            var header = "Name;Email;Matricula";
            var row = "Arthur;;6111";
            var result = CsvDelimiterDetector.Method2_FieldCountConsistency(header, row);
            result.Should().Be(';');
        }

        [Fact]
        public void Method2_NullDataRow_FallsBackToHeaderFieldCount()
        {
            // Header has semicolons only
            var result = CsvDelimiterDetector.Method2_FieldCountConsistency("Name;Email;Matricula", null);
            result.Should().Be(';');
        }

        [Fact]
        public void Method2_BothDelimitersConsistent_ReturnsNull()
        {
            // Single-column header — both delimiters produce 1 field each
            var result = CsvDelimiterDetector.Method2_FieldCountConsistency("Name", "Arthur");
            result.Should().BeNull();
        }

        // ---------------------------------------------------------------
        // Detect (stream entry point) — integration of both methods
        // ---------------------------------------------------------------

        [Theory]
        [InlineData("Name,Email,Matricula\r\nArthur,,6111\r\n", ',')]
        [InlineData("Name;Email;Matricula\r\nArthur;;6111\r\n", ';')]
        public void Detect_PlainFile_ReturnsCorrectDelimiter(string csvContent, char expected)
        {
            using var stream = ToStream(csvContent);
            var result = CsvDelimiterDetector.Detect(stream);
            result.Should().Be(expected);
        }

        [Fact]
        public void Detect_ResetsStreamToZeroAfterReading()
        {
            var content = "Name,Email\r\nArthur,a@b.com\r\n";
            using var stream = ToStream(content);
            _ = CsvDelimiterDetector.Detect(stream);
            stream.Position.Should().Be(0);
        }

        [Fact]
        public void Detect_WithBomPrefix_ReturnsCorrectDelimiter()
        {
            // BOM (\uFEFF) prepended, as generated by WizardService
            var content = "\uFEFFName,Email,Matricula\r\nArthur,,6111\r\n";
            using var stream = ToStream(content);
            var result = CsvDelimiterDetector.Detect(stream);
            result.Should().Be(',');
        }

        [Fact]
        public void Detect_WithSepHintLine_IgnoresHintLine()
        {
            // Excel sometimes prepends sep=; before the header
            var content = "sep=;\r\nName;Email;Matricula\r\nArthur;;6111\r\n";
            using var stream = ToStream(content);
            var result = CsvDelimiterDetector.Detect(stream);
            result.Should().Be(';');
        }

        [Fact]
        public void Detect_EqualDelimiterCounts_BothMethodsAmbiguous_Throws()
        {
            // Header "A,B;C" (comma=1, semi=1) → Method1 tie → null
            // Data   "1,2;3"
            //   comma: header→2 fields, data→2 fields → consistent
            //   semi:  header→2 fields, data→2 fields → consistent (both match → Method2 ambiguous → null)
            // Resolve(null, null) → throws
            var input = "A,B;C\r\n1,2;3\r\n";
            using var stream = ToStream(input);
            var act = () => CsvDelimiterDetector.Detect(stream);
            act.Should().Throw<InvalidOperationException>();
        }

        [Fact]
        public void Detect_AmbiguousFile_ThrowsInvalidOperationException()
        {
            // Header "A,B;C,D;E" (comma=2, semi=2) → Method1 tie → null
            // Data   "1,2;3,4;5"
            //   comma: header→3 fields, data→3 fields → consistent → ','
            //   semi:  header→3 fields, data→3 fields → consistent → ';'
            //   Both consistent → Method2 ambiguous → null
            // Resolve(null, null) → throws
            var input = "A,B;C,D;E\r\n1,2;3,4;5\r\n";
            using var stream = ToStream(input);
            var act = () => CsvDelimiterDetector.Detect(stream);
            act.Should().Throw<InvalidOperationException>();
        }

        [Fact]
        public void Detect_EmptyFile_ThrowsInvalidOperationException()
        {
            using var stream = ToStream("   \r\n  \r\n");
            var act = () => CsvDelimiterDetector.Detect(stream);
            act.Should().Throw<InvalidOperationException>().WithMessage("*vazio*");
        }

        // ---------------------------------------------------------------
        // Helper
        // ---------------------------------------------------------------

        private static MemoryStream ToStream(string content)
        {
            var bytes = System.Text.Encoding.UTF8.GetBytes(content);
            return new MemoryStream(bytes);
        }
    }
}
