// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesApp.Data;

#nullable disable

namespace SalesApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421134000_UpdateScrapeConfigCredentials")]
    partial class UpdateScrapeConfigCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            // Note: This is an abbreviated designer file. 
            // In a real environment, EF would generate the full model snapshot here.
            // For manual migration, we rely on the main migration file and the separate ModelSnapshot.cs.
#pragma warning restore 612, 618
        }
    }
}
